### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by nrontsis** [rogual/homebrew-neovim-dot-app#9]
I'm trying to install neovim-dot-app in Mac OS X El Capitan.

I am getting an error when running `brew install --HEAD neovim-dot-app`:

```
==> make NVIM=/usr/local/opt/neovim/bin/nvim
Last 15 lines from /Users/nrontsis/Library/Logs/Homebrew/neovim-dot-app/01.make:
2016-03-03 01:04:18 +0000

make
NVIM=/usr/local/opt/neovim/bin/nvim

VIM=/usr/local/Cellar/neovim/0.1.2/share/nvim NVIM=/usr/local/opt/neovim/bin/nvim scons -Q
AttributeError: 'NoneType' object has no attribute 'groups':
  File "/private/tmp/neovim-dot-app20160303-91986-v4vglr/SConstruct", line 36:
    ver = re.match(r'NVIM v(\d+)\.(\d+).(\d+)(?:-(\d+))?', ver_str).groups()
make: *** [all] Error 2

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/rogual/homebrew-neovim-dot-app/issues
```

Thanks!

**Comment by rogual** [comment]
Could you give me the output of `/usr/local/opt/neovim/bin/nvim --version`?

**Comment by nrontsis** [comment]
Hi @rogual,

Thanks for the prompt reply!

`/usr/local/opt/neovim/bin/nvim --version` gives:

```
NVIM 0.1.2
Build type: RelWithDebInfo
Compilation: /usr/local/Library/ENV/4.3/clang -Wconversion -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/tmp/neovim20160303-67863-rixc40/neovim-0.1.2/build/config -I/tmp/neovim20160303-67863-rixc40/neovim-0.1.2/src -I/tmp/neovim20160303-67863-rixc40/neovim-0.1.2/deps-build/usr/include -I/tmp/neovim20160303-67863-rixc40/neovim-0.1.2/deps-build/usr/include -I/tmp/neovim20160303-67863-rixc40/neovim-0.1.2/deps-build/usr/include/luajit-2.0 -I/tmp/neovim20160303-67863-rixc40/neovim-0.1.2/deps-build/usr/include -I/tmp/neovim20160303-67863-rixc40/neovim-0.1.2/deps-build/usr/include -I/tmp/neovim20160303-67863-rixc40/neovim-0.1.2/deps-build/usr/include -I/tmp/neovim20160303-67863-rixc40/neovim-0.1.2/deps-build/usr/include -I/usr/local/opt/gettext/include -I/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include -I/tmp/neovim20160303-67863-rixc40/neovim-0.1.2/build/src/nvim/auto -I/tmp/neovim20160303-67863-rixc40/neovim-0.1.2/build/include
Compiled by nrontsis@***.local

Optional features included (+) or not (-): +acl   +iconv    +jemalloc 
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.1.2/share/nvim"
```

**Comment by rogual** [comment]
Hi @nrontsis, this was caused by a bug in the code that checks your Neovim is new enough. I've just committed a fix for this.

However, your Neovim is still too old, so you'll just get a proper error message instead of a backtrace.

You have two options:
1. Use a recent build of Neovim (https://github.com/justinmk/neovim/commit/99d4c8c29c4a9371c268cc20e4805709d86fb686 or newer)  with a recent build of Neovim.app (https://github.com/rogual/neovim-dot-app/commit/d52e252299736cbd588011abb6e88ce1fd4b9d40 or newer). If you installed Neovim through Homebrew this should just be a case of running `brew reinstall --HEAD neovim`.
2. Use an older build of Neovim.app with an older build of Neovim (any commits before those specified above).

Sorry for the inconvenience, breaking changes are always a pain. This issue should go away when Neovim 0.1.3 is out, or when Neovim.app finally starts doing numbered releases.

**Comment by tengomucho** [comment]
I have a similar issue. When installing neovim-dot-app, I see this message:

Your Neovim is too old. Please update Neovim to the latest HEAD and recompile it.

```
Your version: 0.1.3-0
Required: 0.1.3-202

make: *** [all] Error 255
```

However I just upgraded neovim! when I ask for its version, it says:

```
$ nvim --version
NVIM 0.1.3-dev
Build type: Dev
```

etc etc...

Any hint on how to fix this?

**Comment by rogual** [comment]
My reply to the OP above should also apply to your situation, @dirac3000. How did you install neovim?

**Comment by rogual** [comment]
@nrontsis I've just pushed a commit that defines a stable release of Neovim.app which should be compatible with your Neovim 0.1.2. Try installing Neovim.app without `--HEAD` to get the compatible version, if you don't want to use a newer Neovim.

**Comment by nrontsis** [comment]
@rogual As suggested, I updated to Neovim 0.1.3-dev using `brew reinstall --HEAD neovim`.

However, this installed Neovim 0.1.3-0, and neovim-dot-app (`HEAD`) said that the minimum was 0.1.3-202.

Installing without the `--HEAD` option proceeded successfully :)

**Comment by rogual** [comment]
I don't know why some people's NVIM reports 0.1.3-dev. Mine reports 0.1.3-xxx where xxx is the number of commits since the 0.1.3 tag. I'll have to look into this.

**Comment by tengomucho** [comment]
Thank your your answer! I just reinstalled neovim with `brew reinstall neovim` and it still does not work. I switched to the 0.1.2 version of neovim and it still says:

```
...

git reset --hard origin/master
HEAD is now at 687d6fa Fix to Neovim version detection in build script
==> make NVIM=/usr/local/opt/neovim/bin/nvim
VIM=/usr/local/Cellar/neovim/0.1.2/share/nvim NVIM=/usr/local/opt/neovim/bin/nvim icons -Q

Your Neovim is too old. Please update Neovim to the latest HEAD and recompile it.

Your version: 0.1.2-0
Required: 0.1.3-202

```

I was wondering if it might be the make system that is checking for a specific version?

**Comment by rogual** [comment]
I've tagged a Neovim.app release as 0.1.2 — this commit should be compatible with Neovim 0.1.2. It looks like you're still using Neovim.app's HEAD version with Neovim 0.1.2, which won't work. You need both Neovim and Neovim.app to be 0.1.2, or both to be HEAD.

**Comment by rogual** [comment]
To clarify:

```
brew uninstall neovim
brew uninstall neovim-dot-app
brew update

# If you want the bleeding edge
brew install --HEAD neovim
brew install --HEAD neovim-dot-app

# If you want 0.1.2
brew install neovim-dot-app
```

**Comment by tengomucho** [comment]
Ok I see, I got confused, it works fine with 0.1.2. Thanks!
